# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_type_to_string: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    avoid_annotating_with_dynamic: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_void_async: true
    cascade_invocations: true
    directives_ordering: true
    join_return_with_assignment: true
    constant_identifier_names: false
    prefer_single_quotes: true
    require_trailing_commas: true
    omit_local_variable_types: true
    prefer_final_locals: true
    prefer_null_aware_method_calls: true
    sized_box_shrink_expand: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    use_if_null_to_convert_nulls_to_bools: true